# Bootstrap makefile: makes `make` work even before ./configure has run.
#
# GNU make reads GNUmakefile in preference to Makefile, so this bootstrap is
# used until (and even after) the real Makefile has been generated by
# ./configure. Goals reach it through the catch-all rule below, so a target
# added to Makefile.in is reachable without being listed here as well.
#
# This is free software released under the GPL-3.0-or-later.

.DEFAULT_GOAL := all

# Keep the catch-all from being applied to the makefiles themselves: make tries
# to "remake" the makefiles it read, which would forward GNUmakefile to the
# generated Makefile on every run.
GNUmakefile Makefile: ;

# ensure is phony, so it is always out of date and every goal that depends on it
# always forwards — even when a file shares the goal's name.
#
# Homebrew's ncurses is keg-only, so pkg-config cannot see it unaided and a bare
# ./configure silently falls back to the SDK's non-wide ncurses, which the TUI
# does not compile against. Point pkg-config at it when brew has it, so a fresh
# checkout builds with a plain `make` as documented.
.PHONY: ensure
ensure:
	@if [ ! -f Makefile ]; then \
		echo "Makefile not found; running ./configure ..."; \
		ncurses_pc=""; \
		if command -v brew >/dev/null 2>&1; then \
			ncurses_pc="$$(brew --prefix ncurses 2>/dev/null)/lib/pkgconfig"; \
			[ -d "$$ncurses_pc" ] || ncurses_pc=""; \
		fi; \
		if [ -n "$$ncurses_pc" ]; then \
			echo "  using Homebrew ncurses ($$ncurses_pc)"; \
			PKG_CONFIG_PATH="$$ncurses_pc$${PKG_CONFIG_PATH:+:$$PKG_CONFIG_PATH}" ./configure; \
		else \
			./configure; \
		fi; \
	fi

# Any goal: make sure the generated Makefile exists, then run the goal there.
%: ensure
	@$(MAKE) --no-print-directory -f Makefile $@

# clean and distclean are the only goals that must work with no generated
# Makefile at all, so they do not go through ensure.
.PHONY: clean distclean
clean:
	@if [ -f Makefile ]; then $(MAKE) --no-print-directory -f Makefile clean; \
	else echo "nothing to clean (no Makefile)"; fi

distclean: clean
	rm -f Makefile config.log config.status
