# Bootstrap makefile: makes `make` work even before ./configure has run.
#
# GNU make reads GNUmakefile in preference to Makefile, so this bootstrap is
# used until (and even after) the real Makefile has been generated by
# ./configure. Every target ensures the generated Makefile exists, then
# forwards to it. This means a plain `make` always works from a fresh checkout.
#
# This is free software released under the GPL-3.0-or-later.

# Any goal the user asks for is forwarded to the generated Makefile after
# ensuring configure has run. `ensure` regenerates the Makefile if missing.
.PHONY: all build lib cli tui check test lint analyze install uninstall clean distclean ensure

# Default goal.
all build: ensure
	@$(MAKE) --no-print-directory -f Makefile all

lib cli tui check test lint analyze install uninstall: ensure
	@$(MAKE) --no-print-directory -f Makefile $@

ensure:
	@if [ ! -f Makefile ]; then \
		echo "Makefile not found; running ./configure ..."; \
		./configure; \
	fi

clean:
	@if [ -f Makefile ]; then $(MAKE) --no-print-directory -f Makefile clean; \
	else echo "nothing to clean (no Makefile)"; fi

# Full reset: also remove the generated Makefile and configure logs.
distclean: clean
	rm -f Makefile config.log config.status
